Remove image pull. Disable rootfs check

diff --git a/.github/workflows/build-neurodesktop-multiarch.yml b/.github/workflows/build-neurodesktop-multiarch.yml
--- a/.github/workflows/build-neurodesktop-multiarch.yml
+++ b/.github/workflows/build-neurodesktop-multiarch.yml
@@ -48,24 +48,18 @@ jobs:
         echo "SHORT_SHA=$SHORT_SHA" >> $GITHUB_ENV
         echo "IMAGEID=$IMAGEID" >> $GITHUB_ENV
         echo "IMAGENAME=$IMAGENAME" >> $GITHUB_ENV
-    - name: Pull latest image from GitHub packages
-      if: ${{ env.GITHUB_RATE_REMAINING > 0 }}
-      run: |
-        echo ${GITHUB_REF}
-        echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $GITHUB_ACTOR --password-stdin
-        {
-          docker pull $IMAGEID:latest \
-            && ROOTFS_CACHE=$(docker inspect --format='{{.RootFS}}' $IMAGEID:latest) \
-            && echo "ROOTFS_CACHE=$ROOTFS_CACHE" >> $GITHUB_ENV
-          CACHE_CMD="--cache-from $IMAGEID"
-        } || echo "$IMAGEID not found. Resuming build..."
-        echo "CACHE_CMD=$CACHE_CMD" >> $GITHUB_ENV
-    # - name: Modify Dockerfile for CI build
+    # - name: Pull latest image from GitHub packages
     #   if: ${{ env.GITHUB_RATE_REMAINING > 0 }}
     #   run: |
-    #     sed -i 's/# ADD --keep-git-dir=true/ADD --keep-git-dir=true/g' Dockerfile
-    #     sed -i 's/ADD "https:\/\/api.github.com/# ADD "https:\/\/api.github.com/g' Dockerfile
-    #     sed -i 's/RUN git clone https:\/\/github.com\/NeuroDesk\/neurocommand.git/# RUN git clone https:\/\/github.com\/NeuroDesk\/neurocommand.git/g' Dockerfile
+    #     echo ${GITHUB_REF}
+    #     echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $GITHUB_ACTOR --password-stdin
+    #     {
+    #       docker pull $IMAGEID:latest \
+    #         && ROOTFS_CACHE=$(docker inspect --format='{{.RootFS}}' $IMAGEID:latest) \
+    #         && echo "ROOTFS_CACHE=$ROOTFS_CACHE" >> $GITHUB_ENV
+    #       CACHE_CMD="--cache-from $IMAGEID"
+    #     } || echo "$IMAGEID not found. Resuming build..."
+    #     echo "CACHE_CMD=$CACHE_CMD" >> $GITHUB_ENV
     - name: Set up QEMU
       id: qemu
       uses: docker/setup-qemu-action@v1
@@ -84,13 +78,15 @@ jobs:
         # docker buildx build --platform linux/amd64,linux/arm64 . --file Dockerfile --tag $IMAGEID:$SHORT_SHA --cache-from $IMAGEID --label "GITHUB_REPOSITORY=$GITHUB_REPOSITORY" --label "GITHUB_SHA=$GITHUB_SHA"
         # ROOTFS_NEW=$(docker inspect --format='{{.RootFS}}' $IMAGEID:$SHORT_SHA)
         # docker buildx build --load --platform linux/amd64 . --file Dockerfile --tag $IMAGEID:$SHORT_SHA $CACHE_CMD --label "GITHUB_REPOSITORY=$GITHUB_REPOSITORY" --label "GITHUB_SHA=$GITHUB_SHA"
-        docker buildx build --load --platform linux/arm64,linux/amd64 . --file Dockerfile --tag $IMAGEID:$SHORT_SHA --label "GITHUB_REPOSITORY=$GITHUB_REPOSITORY" --label "GITHUB_SHA=$GITHUB_SHA"
-        ROOTFS_NEW=$(docker inspect --format='{{.RootFS}}' $IMAGEID:$SHORT_SHA)
+
+        docker buildx build --load --platform linux/amd64,linux/arm64 . --file Dockerfile --tag $IMAGEID:$SHORT_SHA --label "GITHUB_REPOSITORY=$GITHUB_REPOSITORY" --label "GITHUB_SHA=$GITHUB_SHA"
+        # ROOTFS_NEW=$(docker inspect --format='{{.RootFS}}' $IMAGEID:$SHORT_SHA)
+
         # docker buildx build --platform linux/amd64,linux/arm64 . --file Dockerfile --tag $IMAGEID:$SHORT_SHA --cache-from $IMAGEID --label "GITHUB_REPOSITORY=$GITHUB_REPOSITORY" --label "GITHUB_SHA=$GITHUB_SHA"
         # ROOTFS_NEW=$(docker inspect --format='{{.RootFS}}' $IMAGEID:$SHORT_SHA)
-        echo "ROOTFS_NEW=$ROOTFS_NEW" >> $GITHUB_ENV
+        # echo "ROOTFS_NEW=$ROOTFS_NEW" >> $GITHUB_ENV
     - name: Push image to GitHub packages (if changes found)
-      if: ${{ github.event.inputs.force_push == 'true' || (env.GITHUB_RATE_REMAINING > 0 && env.ROOTFS_NEW != env.ROOTFS_CACHE) }}
+      # if: ${{ github.event.inputs.force_push == 'true' || (env.GITHUB_RATE_REMAINING > 0 && env.ROOTFS_NEW != env.ROOTFS_CACHE) }}
       run: |
         # Push to GH Packages
         docker tag $IMAGEID:$SHORT_SHA $IMAGEID:$BUILDDATE
